spring:
  application:
  name: Remoter-Client


#####################################################################################################
# 日志
logging:
  level:
    root: DEBUG
    com.aoligei.remoter: INFO
    sun: ERROR
    javax: INFO
    java.awt: ERROR
    io.netty: INFO
    org.apache.catalina: INFO
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss